[2023-12-08T00:28:06.299+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: good_morning_1.get_cur_rate scheduled__2023-12-08T00:27:00+00:00 [queued]>
[2023-12-08T00:28:06.324+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: good_morning_1.get_cur_rate scheduled__2023-12-08T00:27:00+00:00 [queued]>
[2023-12-08T00:28:06.325+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-08T00:28:06.361+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): get_cur_rate> on 2023-12-08 00:27:00+00:00
[2023-12-08T00:28:06.378+0000] {standard_task_runner.py:57} INFO - Started process 6447 to run task
[2023-12-08T00:28:06.387+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'good_morning_1', 'get_cur_rate', 'scheduled__2023-12-08T00:27:00+00:00', '--job-id', '665', '--raw', '--subdir', 'DAGS_FOLDER/good_mornig.py', '--cfg-path', '/tmp/tmp40tj1sl3']
[2023-12-08T00:28:06.395+0000] {standard_task_runner.py:85} INFO - Job 665: Subtask get_cur_rate
[2023-12-08T00:28:06.508+0000] {task_command.py:416} INFO - Running <TaskInstance: good_morning_1.get_cur_rate scheduled__2023-12-08T00:27:00+00:00 [running]> on host 1ab12098bb1e
[2023-12-08T00:28:06.708+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mdv' AIRFLOW_CTX_DAG_ID='good_morning_1' AIRFLOW_CTX_TASK_ID='get_cur_rate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T00:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-08T00:27:00+00:00'
[2023-12-08T00:28:06.771+0000] {docker.py:343} INFO - Starting docker container from image masalskii/ex-rate
[2023-12-08T00:28:06.788+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2023-12-08T00:28:08.411+0000] {docker.py:413} INFO - ['exchangerate.py', 'l', 'BTC', 'RUB']
[2023-12-08T00:28:18.432+0000] {docker.py:413} INFO - Error occured: HTTPConnectionPool(host='api.exchangerate.host', port=80): Max retries exceeded with url: /live?access_key=3b41539862f298ff27d084d3aa2a3549&currencies=RUB&source=BTC (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f83d486baf0>: Failed to resolve 'api.exchangerate.host' ([Errno -3] Temporary failure in name resolution)"))
[2023-12-08T00:28:18.748+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=good_morning_1, task_id=get_cur_rate, execution_date=20231208T002700, start_date=20231208T002806, end_date=20231208T002818
[2023-12-08T00:28:18.807+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-08T00:28:18.850+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
